### ISSUE TITLE
MCD

### ISSUE THREAD

**Issue by FlorianBruniaux** [MIM-TPZ/scaping_data_consumer#1]

**Comment by Khalindr** [comment]
![mcd](https://user-images.githubusercontent.com/23277486/36022407-56932dae-0d89-11e8-8f6a-af274eea9765.png)

**Comment by dat-Antho** [comment]
![mcd](https://user-images.githubusercontent.com/16465475/36022876-eaa2c8d2-0d8a-11e8-99f1-a3be3331254f.PNG)

**Comment by FlorianBruniaux** [comment]
Good on valide et on close
