### ISSUE TITLE
Class diagram

### ISSUE THREAD

**Issue by FlorianBruniaux** [MIM-TPZ/scaping_data_consumer#2]

**Comment by DoreenDaunique** [comment]
![diagclassev1](https://user-images.githubusercontent.com/32064776/36022414-5c128d6a-0d89-11e8-9da3-2d72c4a7e561.png)

**Comment by Khalindr** [comment]
![bdd](https://user-images.githubusercontent.com/23277486/36022934-14e3a4fe-0d8b-11e8-9cab-2ef59ab656bf.png)

**Comment by Jintarei** [comment]
![diagramme_class](https://user-images.githubusercontent.com/16443813/36022953-1c55ee40-0d8b-11e8-824d-c9537663ba52.png)

**Comment by tcrepy** [comment]
![capture](https://user-images.githubusercontent.com/22787876/36022974-2b88653c-0d8b-11e8-9b2c-9dad6b925770.PNG)

**Comment by FlorianBruniaux** [comment]
Good on valide on close

**Comment by FlorianBruniaux** [comment]
![bdd](https://user-images.githubusercontent.com/3902606/37877480-4a4d0790-305c-11e8-8a1f-80715ca8b837.png)
